baseurl: "https://weibinqu.xyz"
languageCode: "en-us"
title: "Weibin QU | 瞿伟斌"
theme: "hugo-ivy"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 100

permalinks:
  cn: "/cn/:year/:month/:slug/"
  en: "/en/:year/:month/:slug/"

menu:
  main:
    - name: "About"
      url: "/en/about/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "关于"
      url: "/cn/about/"
      weight: 3
    - name: "博客"
      url: "/cn/"
      weight: 4
  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/en/about/"
      weight: 2
    - name: "Blog"
      url: "/en/"
      weight: 3
    - name: "中文"
      url: "/cn/"
      weight: 4
  cn:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/cn/about/"
      weight: 2
    - name: "博客"
      url: "/cn/"
      weight: 3
    - name: "English"
      url: "/en/"
      weight: 4


params:
    description: "A Blog of WeiBin Qu."
    footer : "&copy; [Weibin Qu](https://weibinqu.xyz) 2017 | [Github](https://github.com/weibinfighting) | [Weibo](https://weibo.com/p/1005055533220082/home?from=page_100505&mod=TAB#place)"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion : "9.12.0"
    highlightjsCDN : "//cdn.bootcss.com"
    highlightjsLang : ["r", "yaml","tex"]
    highlightjsTheme : "github"

    MathJaxCDN : "//cdn.bootcss.com"
    MathJaxVersion : "2.7.1"

logo:
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

author:
    en: "Weibin Qu"
    cn: "瞿伟斌"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false