baseurl = "https://weibinqu.xyz"
languageCode = "en-us"
title = "Weibin QU| 瞿伟斌"
theme = "hugo-lithium"
canonifyurls = true
relativeurls = true
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[params]
    description = "A Blog of WeiBin Qu."
    github = "https://github.com/weibinfighting"
    email = "qubinhan@gmail.com"
    footer = "&copy; [Weibin Qu](https://weibinqu.xyz) 2016-2024 | [Github](https://github.com/weibinfighting)"
    # options for highlight.js (version, additional languages, and theme)
    # customJS = ["js/external-link.js", "js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js", "js/math-code.js"]
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"
    fullWidthTheme = false
    centerTheme = false
    [params.logo]
    url = "favicon.ico.png"
    width = 50
    height = 50
    alt = "Logo"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url ="/en-about"
    weight = 2
[[menu.main]]
    name = "关于"
    url = "/cn-about/"
    weight = 3
[[menu.main]]
    name = "博客"
    url = "/cn/"
    weight = 4
[[menu.main]] 
    name = "Blog"
    url = "/en-about"
    weight = 5


#[blackfriday]
#    extensionsmask = ["noIntraEmphasis"]
#    fractions = false
